# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sobol_owen_cpp <- function(N, dim, seed_in, scramble) {
    .Call(`_sensobol_sobol_owen_cpp`, N, dim, seed_in, scramble)
}

mmult <- function(A, x) {
    .Call(`_sensobol_mmult`, A, x)
}

